# Scalafix Configuration for linthis-plugin-template Plugin
# Documentation: https://scalacenter.github.io/scalafix/

rules = [
  OrganizeImports,
  DisableSyntax,
  LeakingImplicitClassVal,
  NoAutoTupling,
  NoValInForComprehension,
  ProcedureSyntax,
  RedundantSyntax
]

DisableSyntax.noVars = true
DisableSyntax.noThrows = false
DisableSyntax.noNulls = true
DisableSyntax.noReturns = true
DisableSyntax.noAsInstanceOf = false
DisableSyntax.noIsInstanceOf = false
DisableSyntax.noXml = true
DisableSyntax.noFinalVal = true
DisableSyntax.noFinalize = true

OrganizeImports {
  groups = [
    "re:javax?\\.",
    "scala.",
    "*",
    "com.example."
  ]
  removeUnused = true
  groupedImports = Merge
}
